version: '3.7'
services:
  airflow:
    image: dataeng-dibimbing/airflow
    container_name: ${AIRFLOW_CONTAINER_NAME}
    hostname: ${AIRFLOW_HOST_NAME}
    entrypoint: /scripts/airflow_entrypoint.sh
    restart: always
    environment:
      - DW_POSTGRES_URI=${DW_POSTGRES_URI}
    volumes:
      - ../dags:/opt/airflow/dags
      - ../data:/opt/airflow/data
      - ../scripts:/scripts
    ports:
      - ${AIRFLOW_WEBSERVER_PORT}:8080
    networks:
      - dataeng-network
  
  metabase:
    image: metabase/metabase:v0.47.3
    container_name: ${METABASE_CONTAINER_NAME}
    hostname: ${METABASE_HOST_NAME}
    ports:
      - "${METABASE_PORT}:3000"
    restart: always
    networks:
      - dataeng-network
  
  metabase-setup:
    image: bash:5.1.16
    container_name: metabase-setup
    volumes:
      - ../scripts:/tmp
    depends_on:
      - metabase
    environment:
      - DW_POSTGRES_URI=${DW_POSTGRES_URI}
      - MB_USER_EMAIL=${METABASE_USER_EMAIL}
      - MB_USER_PASSWORD=${METABASE_USER_PASSWORD}
      - MB_USER_FIRST_NAME=${METABASE_USER_FIRST_NAME}
      - MB_USER_LAST_NAME=${METABASE_USER_LAST_NAME}
    command: sh /tmp/metabase_entrypoint.sh ${METABASE_CONTAINER_NAME}:3000
    networks:
      - dataeng-network
  
  postgres:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - dataeng-network

  postgres-dw:
    image: postgres:latest
    container_name: postgres-dw
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DW_DB}
      POSTGRES_USER: ${POSTGRES_DW_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DW_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - dataeng-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - ${PGADMIN_PORT}:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - dataeng-network

volumes:
  postgres-data:
  pgadmin-data:

networks:
  dataeng-network:
    external: true
